using System.Collections.Immutable;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Macaron.InlineInterface.Tests;

[TestFixture]
public class InlineInterfaceGeneratorTests
{
    private static (ImmutableArray<Diagnostic> diagnostics, string[] generatedCodes) CompileAndGetResults<T>(
        string sourceCode,
        Assembly[]? additionalAssemblies = null
    ) where T : IIncrementalGenerator, new()
    {
        var references = AppDomain
            .CurrentDomain
            .GetAssemblies()
            .Concat(additionalAssemblies ?? [])
            .Where(assembly => !assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>()
            .ToImmutableArray();

        var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
        var compilation = CSharpCompilation.Create(
            assemblyName: "Macaron.InlineInterface.Tests",
            syntaxTrees: [syntaxTree],
            references: references,
            options: new CSharpCompilationOptions(
                outputKind: OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );

        var generator = new T();
        var driver = CSharpGeneratorDriver.Create(generator);

        var result = driver.RunGenerators(compilation).GetRunResult().Results.Single();
        var generatedSources = result.GeneratedSources;
        var generatedCodes = generatedSources.Select(source => source.SourceText.ToString()).ToArray();

        var allDiagnostics = compilation.GetDiagnostics()
            .Concat(result.Diagnostics)
            .ToImmutableArray();

        return (allDiagnostics, generatedCodes);
    }

    private static void AssertGeneratedCode(string sourceCode, string[] expectedCodes)
    {
        var (_, generatedCodes) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        Assert.That(generatedCodes, Has.Length.EqualTo(expectedCodes.Length));

        foreach (var (generatedCode, index) in generatedCodes.Select((code, index) => (code, index)))
        {
            Assert.That(
                actual: generatedCode.ReplaceLineEndings(),
                expression: Is.EqualTo(expectedCodes[index].ReplaceLineEndings())
            );
        }
    }

    private static void AssertGeneratedCode(string sourceCode, int sourceIndex, string expected)
    {
        var (_, generatedCodes) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        Assert.That(
            actual: generatedCodes[sourceIndex].ReplaceLineEndings(),
            expression: Is.EqualTo(expected.ReplaceLineEndings())
        );
    }

    private static void AssertGeneratedCode(string sourceCode, string expected)
    {
        AssertGeneratedCode(sourceCode, sourceIndex: 0, expected);
    }

    private static void AssertDiagnostic(string sourceCode, string expectedDiagnosticId)
    {
        var (diagnostics, _) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        var actualDiagnosticIds = diagnostics
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Select(diagnostic => diagnostic.Id)
            .ToArray();

        Assert.That(actualDiagnosticIds, Has.Some.Matches(expectedDiagnosticId));
    }

    [Test]
    public void When_ImplementationOfMethodUsed_Should_GenerateBuilderAndExtensionMethods()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;

            namespace Macaron.InlineInterface.Tests;

            public class Foo { }

            public class Parent<T> where T : class
            {
                public interface IPerson<T> where T : struct
                {
                    T GetName();

                    void SetName(T name);

                    string? FirstName { get; internal set; }

                    string LastName { get; }
                }
            }

            public class TestClass
            {
                public void TestMethod()
                {
                    var implementationOf = Implementation.Of<Parent<string>.IPerson<int>>();
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests
            {
                internal readonly struct Parent_1_IPerson_1Builder<T0, T1>
                    where T0 : class
                    where T1 : struct
                {
                    private sealed class Impl : global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>
                    {
                        private readonly global::System.Func<string?>? _getFirstName;
                        private readonly global::System.Action<string?>? _setFirstName;
                        private readonly global::System.Func<string>? _getLastName;
                        private readonly global::System.Func<T1>? _method_GetName_0;
                        private readonly global::System.Action<T1>? _method_SetName_0;

                        public Impl(
                            global::System.Func<string?>? getFirstName,
                            global::System.Action<string?>? setFirstName,
                            global::System.Func<string>? getLastName,
                            global::System.Func<T1>? method_GetName_0,
                            global::System.Action<T1>? method_SetName_0)
                        {
                            _getFirstName = getFirstName;
                            _setFirstName = setFirstName;
                            _getLastName = getLastName;
                            _method_GetName_0 = method_GetName_0;
                            _method_SetName_0 = method_SetName_0;
                        }

                        string? global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>.FirstName
                        {
                            get => (_getFirstName ?? throw new global::System.NotImplementedException())();
                            set => (_setFirstName ?? throw new global::System.NotImplementedException())(value);
                        }

                        string global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>.LastName
                        {
                            get => (_getLastName ?? throw new global::System.NotImplementedException())();
                        }

                        T1 global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>.GetName() => (_method_GetName_0 ?? throw new global::System.NotImplementedException())();

                        void global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>.SetName(T1 name) => (_method_SetName_0 ?? throw new global::System.NotImplementedException())(name);
                    }

                    private readonly bool _allowMissingImplementation;

                    private readonly global::System.Func<string?>? GetFirstName { get; init; } = null;

                    private readonly global::System.Action<string?>? SetFirstName { get; init; } = null;

                    private readonly global::System.Func<string>? GetLastName { get; init; } = null;

                    private readonly global::System.Func<T1>? Method_GetName_0 { get; init; } = null;

                    private readonly global::System.Action<T1>? Method_SetName_0 { get; init; } = null;

                    public Parent_1_IPerson_1Builder(
                        bool allowMissingImplementation,
                        global::System.Func<string?>? getFirstName = null,
                        global::System.Action<string?>? setFirstName = null,
                        global::System.Func<string>? getLastName = null,
                        global::System.Func<T1>? method_GetName_0 = null,
                        global::System.Action<T1>? method_SetName_0 = null)
                    {
                        _allowMissingImplementation = allowMissingImplementation;

                        GetFirstName = getFirstName;
                        SetFirstName = setFirstName;
                        GetLastName = getLastName;
                        Method_GetName_0 = method_GetName_0;
                        Method_SetName_0 = method_SetName_0;
                    }

                    public Parent_1_IPerson_1Builder<T0, T1> FirstName(global::System.Func<string?> getter, global::System.Action<string?> setter) => this with { GetFirstName = getter, SetFirstName = setter };

                    public Parent_1_IPerson_1Builder<T0, T1> LastName(global::System.Func<string> getter) => this with { GetLastName = getter };

                    public Parent_1_IPerson_1Builder<T0, T1> GetName(global::System.Func<T1> impl) => this with { Method_GetName_0 = impl };

                    public Parent_1_IPerson_1Builder<T0, T1> SetName(global::System.Action<T1> impl) => this with { Method_SetName_0 = impl };

                    public global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build(global::Macaron.InlineInterface.Tag _ = default)
                    {
                        return new Impl(
                            getFirstName: GetFirstName ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            setFirstName: SetFirstName ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            getLastName: GetLastName ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            method_GetName_0: Method_GetName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            method_SetName_0: Method_SetName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()));
                    }
                }
            }

            namespace Macaron.InlineInterface
            {
                internal static partial class ImplementationOfExtensions
                {
                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> FirstName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<string?> getter,
                        global::System.Action<string?> setter)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, getFirstName: getter, setFirstName: setter);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> LastName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<string> getter)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, getLastName: getter);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> GetName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<T1> impl)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, method_GetName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> SetName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Action<T1> impl)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, method_SetName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::Macaron.InlineInterface.Tag _ = default)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation).Build(_);
                    }
                }
            }

            """
        );
    }

    [Test]
    public void When_InterfaceHasEventMember_Should_GenerateEventCollection()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;

            namespace Macaron.InlineInterface.Tests;

            public class Foo { }

            public class Parent<T>
            {
                public interface IPerson<T>
                {
                    event Func<Foo?, string> NameChanged;

                    void SetName(string name);

                    string LastName { get; }
                }
            }

            public class TestClass
            {
                public void TestMethod()
                {
                    var implementationOf = Implementation.Of<Parent<string>.IPerson<int>>();
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests
            {
                internal readonly struct Parent_1_IPerson_1Builder<T0, T1>
                {
                    public sealed class EventCollection
                    {
                        public global::System.Func<global::Macaron.InlineInterface.Tests.Foo?, string>? NameChanged_0;
                    }

                    public sealed class EventDispatcher
                    {
                        private readonly EventCollection _eventCollection;

                        public EventDispatcher(EventCollection eventCollection)
                        {
                            _eventCollection = eventCollection;
                        }

                        public string? InvokeNameChanged(global::Macaron.InlineInterface.Tests.Foo? arg)
                        {
                            if (_eventCollection.NameChanged_0 == null) return default;
                            return _eventCollection.NameChanged_0(arg);
                        }
                    }

                    private sealed class Impl : global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>
                    {
                        private readonly EventCollection _eventCollection = new();
                        private readonly EventDispatcher _eventDispatcher;
                        private readonly global::System.Func<EventCollection, string>? _getLastName;
                        private readonly global::System.Action<EventDispatcher, string>? _method_SetName_0;

                        public Impl(
                            global::System.Func<EventCollection, string>? getLastName,
                            global::System.Action<EventDispatcher, string>? method_SetName_0)
                        {
                            _eventDispatcher = new EventDispatcher(_eventCollection);
                            _getLastName = getLastName;
                            _method_SetName_0 = method_SetName_0;
                        }

                        event global::System.Func<global::Macaron.InlineInterface.Tests.Foo?, string>? global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>.NameChanged
                        {
                            add => _eventCollection.NameChanged_0 += value;
                            remove => _eventCollection.NameChanged_0 -= value;
                        }

                        string global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>.LastName
                        {
                            get => (_getLastName ?? throw new global::System.NotImplementedException())(_eventCollection);
                        }

                        void global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>.SetName(string name) => (_method_SetName_0 ?? throw new global::System.NotImplementedException())(_eventDispatcher, name);
                    }

                    private readonly bool _allowMissingImplementation;

                    private readonly global::System.Func<EventCollection, string>? GetLastName { get; init; } = null;

                    private readonly global::System.Action<EventDispatcher, string>? Method_SetName_0 { get; init; } = null;

                    public Parent_1_IPerson_1Builder(
                        bool allowMissingImplementation,
                        global::System.Func<EventCollection, string>? getLastName = null,
                        global::System.Action<EventDispatcher, string>? method_SetName_0 = null)
                    {
                        _allowMissingImplementation = allowMissingImplementation;

                        GetLastName = getLastName;
                        Method_SetName_0 = method_SetName_0;
                    }

                    public Parent_1_IPerson_1Builder<T0, T1> LastName(global::System.Func<EventCollection, string> getter) => this with { GetLastName = getter };

                    public Parent_1_IPerson_1Builder<T0, T1> SetName(global::System.Action<EventDispatcher, string> impl) => this with { Method_SetName_0 = impl };

                    public global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build(global::Macaron.InlineInterface.Tag _ = default)
                    {
                        return new Impl(
                            getLastName: GetLastName ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            method_SetName_0: Method_SetName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()));
                    }
                }
            }

            namespace Macaron.InlineInterface
            {
                internal static partial class ImplementationOfExtensions
                {
                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> LastName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>.EventCollection, string> getter)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, getLastName: getter);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> SetName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Action<global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>.EventDispatcher, string> impl)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, method_SetName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::Macaron.InlineInterface.Tag _ = default)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation).Build(_);
                    }
                }
            }

            """
        );
    }

    [Test]
    public void When_InterfaceHasInheritance_Should_GenerateInheritanceMembers()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;

            namespace Macaron.InlineInterface.Tests
            {
                namespace Inner
                {
                    public interface IFoo<T>
                    {
                        event Func<T?> NameChanged;

                        string GetLastName();
                    }
                }

                public interface IBar<T>
                {
                    event Action NameChanged;

                    string GetFirstName();

                    string GetLastName();
                }

                public interface IBaz<T> : IBar<int>
                {
                    void SetName(string name);

                    string GetLastName(int index);
                }

                public class Foo<T>
                {
                    public interface IFooBar<T, U> : Inner.IFoo<T>, IBaz<U>
                    {
                        event Action<string, int> ValueChanged;
                    }
                }

                public class TestClass
                {
                    public void TestMethod()
                    {
                        var implementationOf = Implementation.Of<Foo<float>.IFooBar<string, int>>();
                    }
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests
            {
                internal readonly struct Foo_1_IFooBar_2Builder<T0, T1, T2>
                {
                    public sealed class EventCollection
                    {
                        public global::System.Action<string, int>? ValueChanged_0;
                        public global::System.Func<T1?>? NameChanged_0;
                        public global::System.Action? NameChanged_1;
                    }

                    public sealed class EventDispatcher
                    {
                        private readonly EventCollection _eventCollection;

                        public EventDispatcher(EventCollection eventCollection)
                        {
                            _eventCollection = eventCollection;
                        }

                        public void RaiseValueChanged(string arg1, int arg2)
                        {
                            if (_eventCollection.ValueChanged_0 == null) return;
                            _eventCollection.ValueChanged_0(arg1, arg2);
                        }

                        public T1? InvokeNameChanged()
                        {
                            if (_eventCollection.NameChanged_0 == null) return default;
                            return _eventCollection.NameChanged_0();
                        }

                        public void RaiseNameChanged()
                        {
                            if (_eventCollection.NameChanged_1 == null) return;
                            _eventCollection.NameChanged_1();
                        }
                    }

                    private sealed class Impl : global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2>
                    {
                        private readonly EventCollection _eventCollection = new();
                        private readonly EventDispatcher _eventDispatcher;
                        private readonly global::System.Func<EventDispatcher, string>? _method_GetLastName_0;
                        private readonly global::System.Func<EventDispatcher, int, string>? _method_GetLastName_1;
                        private readonly global::System.Action<EventDispatcher, string>? _method_SetName_0;
                        private readonly global::System.Func<EventDispatcher, string>? _method_GetFirstName_0;

                        public Impl(
                            global::System.Func<EventDispatcher, string>? method_GetLastName_0,
                            global::System.Func<EventDispatcher, int, string>? method_GetLastName_1,
                            global::System.Action<EventDispatcher, string>? method_SetName_0,
                            global::System.Func<EventDispatcher, string>? method_GetFirstName_0)
                        {
                            _eventDispatcher = new EventDispatcher(_eventCollection);
                            _method_GetLastName_0 = method_GetLastName_0;
                            _method_GetLastName_1 = method_GetLastName_1;
                            _method_SetName_0 = method_SetName_0;
                            _method_GetFirstName_0 = method_GetFirstName_0;
                        }

                        event global::System.Action<string, int>? global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2>.ValueChanged
                        {
                            add => _eventCollection.ValueChanged_0 += value;
                            remove => _eventCollection.ValueChanged_0 -= value;
                        }

                        event global::System.Func<T1?>? global::Macaron.InlineInterface.Tests.Inner.IFoo<T1>.NameChanged
                        {
                            add => _eventCollection.NameChanged_0 += value;
                            remove => _eventCollection.NameChanged_0 -= value;
                        }

                        event global::System.Action? global::Macaron.InlineInterface.Tests.IBar<int>.NameChanged
                        {
                            add => _eventCollection.NameChanged_1 += value;
                            remove => _eventCollection.NameChanged_1 -= value;
                        }

                        string global::Macaron.InlineInterface.Tests.Inner.IFoo<T1>.GetLastName() => (_method_GetLastName_0 ?? throw new global::System.NotImplementedException())(_eventDispatcher);

                        void global::Macaron.InlineInterface.Tests.IBaz<T2>.SetName(string name) => (_method_SetName_0 ?? throw new global::System.NotImplementedException())(_eventDispatcher, name);

                        string global::Macaron.InlineInterface.Tests.IBaz<T2>.GetLastName(int index) => (_method_GetLastName_1 ?? throw new global::System.NotImplementedException())(_eventDispatcher, index);

                        string global::Macaron.InlineInterface.Tests.IBar<int>.GetFirstName() => (_method_GetFirstName_0 ?? throw new global::System.NotImplementedException())(_eventDispatcher);

                        string global::Macaron.InlineInterface.Tests.IBar<int>.GetLastName() => (_method_GetLastName_0 ?? throw new global::System.NotImplementedException())(_eventDispatcher);
                    }

                    private readonly bool _allowMissingImplementation;

                    private readonly global::System.Func<EventDispatcher, string>? Method_GetLastName_0 { get; init; } = null;

                    private readonly global::System.Func<EventDispatcher, int, string>? Method_GetLastName_1 { get; init; } = null;

                    private readonly global::System.Action<EventDispatcher, string>? Method_SetName_0 { get; init; } = null;

                    private readonly global::System.Func<EventDispatcher, string>? Method_GetFirstName_0 { get; init; } = null;

                    public Foo_1_IFooBar_2Builder(
                        bool allowMissingImplementation,
                        global::System.Func<EventDispatcher, string>? method_GetLastName_0 = null,
                        global::System.Func<EventDispatcher, int, string>? method_GetLastName_1 = null,
                        global::System.Action<EventDispatcher, string>? method_SetName_0 = null,
                        global::System.Func<EventDispatcher, string>? method_GetFirstName_0 = null)
                    {
                        _allowMissingImplementation = allowMissingImplementation;

                        Method_GetLastName_0 = method_GetLastName_0;
                        Method_GetLastName_1 = method_GetLastName_1;
                        Method_SetName_0 = method_SetName_0;
                        Method_GetFirstName_0 = method_GetFirstName_0;
                    }

                    public Foo_1_IFooBar_2Builder<T0, T1, T2> GetLastName(global::System.Func<EventDispatcher, string> impl) => this with { Method_GetLastName_0 = impl };

                    public Foo_1_IFooBar_2Builder<T0, T1, T2> GetLastName(global::System.Func<EventDispatcher, int, string> impl) => this with { Method_GetLastName_1 = impl };

                    public Foo_1_IFooBar_2Builder<T0, T1, T2> SetName(global::System.Action<EventDispatcher, string> impl) => this with { Method_SetName_0 = impl };

                    public Foo_1_IFooBar_2Builder<T0, T1, T2> GetFirstName(global::System.Func<EventDispatcher, string> impl) => this with { Method_GetFirstName_0 = impl };

                    public global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2> Build(global::Macaron.InlineInterface.Tag _ = default)
                    {
                        return new Impl(
                            method_GetLastName_0: Method_GetLastName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            method_GetLastName_1: Method_GetLastName_1 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            method_SetName_0: Method_SetName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            method_GetFirstName_0: Method_GetFirstName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()));
                    }
                }
            }

            namespace Macaron.InlineInterface
            {
                internal static partial class ImplementationOfExtensions
                {
                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2> GetLastName<T0, T1, T2>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2>> implementationOf,
                        global::System.Func<global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>.EventDispatcher, string> impl)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>(allowMissingImplementation: implementationOf.AllowMissingImplementation, method_GetLastName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2> GetLastName<T0, T1, T2>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2>> implementationOf,
                        global::System.Func<global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>.EventDispatcher, int, string> impl)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>(allowMissingImplementation: implementationOf.AllowMissingImplementation, method_GetLastName_1: impl);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2> SetName<T0, T1, T2>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2>> implementationOf,
                        global::System.Action<global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>.EventDispatcher, string> impl)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>(allowMissingImplementation: implementationOf.AllowMissingImplementation, method_SetName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2> GetFirstName<T0, T1, T2>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2>> implementationOf,
                        global::System.Func<global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>.EventDispatcher, string> impl)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>(allowMissingImplementation: implementationOf.AllowMissingImplementation, method_GetFirstName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2> Build<T0, T1, T2>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Foo<T0>.IFooBar<T1, T2>> implementationOf,
                        global::Macaron.InlineInterface.Tag _ = default)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Foo_1_IFooBar_2Builder<T0, T1, T2>(allowMissingImplementation: implementationOf.AllowMissingImplementation).Build(_);
                    }
                }
            }

            """
        );
    }

    [Test]
    public void When_TargetTypeIsNotInterface_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public class NotAnInterface { }

            public class Test { void M() => Implementation.Of<NotAnInterface>(); }
            """,
            expectedDiagnosticId: "MII0001"
        );
    }

    [Test]
    public void When_TargetTypeIsNullable_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface ITest { }

            public class Test { void M() => Implementation.Of<ITest?>(); }
            """,
            expectedDiagnosticId: "MII0002"
        );
    }

    [Test]
    public void When_TargetTypeHasGenericMethod_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface IWithGenericMethod { void M<T>(T arg); }

            public class Test { void M() => Implementation.Of<IWithGenericMethod>(); }
            """,
            expectedDiagnosticId: "MII0003"
        );
    }

    [Test]
    public void When_TargetTypeHasMethodWithRefParameters_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface IWithRefParam { void M(ref int arg); }

            public class Test { void M() => Implementation.Of<IWithRefParam>(); }
            """,
            expectedDiagnosticId: "MII0004"
        );
    }
}
