using System.Collections.Immutable;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Macaron.InlineInterface.Tests;

[TestFixture]
public class InlineInterfaceGeneratorTests
{
    private static (ImmutableArray<Diagnostic> diagnostics, string[] generatedCodes) CompileAndGetResults<T>(
        string sourceCode,
        Assembly[]? additionalAssemblies = null
    ) where T : IIncrementalGenerator, new()
    {
        var references = AppDomain
            .CurrentDomain
            .GetAssemblies()
            .Concat(additionalAssemblies ?? [])
            .Where(assembly => !assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>()
            .ToImmutableArray();

        var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
        var compilation = CSharpCompilation.Create(
            assemblyName: "Macaron.InlineInterface.Tests",
            syntaxTrees: [syntaxTree],
            references: references,
            options: new CSharpCompilationOptions(
                outputKind: OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );

        var generator = new T();
        var driver = CSharpGeneratorDriver.Create(generator);

        var result = driver.RunGenerators(compilation).GetRunResult().Results.Single();
        var generatedSources = result.GeneratedSources;
        var generatedCodes = generatedSources.Select(source => source.SourceText.ToString()).ToArray();

        var allDiagnostics = compilation.GetDiagnostics()
            .Concat(result.Diagnostics)
            .ToImmutableArray();

        return (allDiagnostics, generatedCodes);
    }

    private static void AssertGeneratedCode(string sourceCode, string[] expectedCodes)
    {
        var (_, generatedCodes) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        Assert.That(generatedCodes, Has.Length.EqualTo(expectedCodes.Length));

        foreach (var (generatedCode, index) in generatedCodes.Select((code, index) => (code, index)))
        {
            Assert.That(
                actual: generatedCode.ReplaceLineEndings(),
                expression: Is.EqualTo(expectedCodes[index].ReplaceLineEndings())
            );
        }
    }

    private static void AssertGeneratedCode(string sourceCode, int sourceIndex, string expected)
    {
        var (_, generatedCodes) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        Assert.That(
            actual: generatedCodes[sourceIndex].ReplaceLineEndings(),
            expression: Is.EqualTo(expected.ReplaceLineEndings())
        );
    }

    private static void AssertGeneratedCode(string sourceCode, string expected)
    {
        AssertGeneratedCode(sourceCode, sourceIndex: 0, expected);
    }

    private static void AssertDiagnostic(string sourceCode, string expectedDiagnosticId)
    {
        var (diagnostics, _) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        var actualDiagnosticIds = diagnostics
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Select(diagnostic => diagnostic.Id)
            .ToArray();

        Assert.That(actualDiagnosticIds, Has.Some.Matches(expectedDiagnosticId));
    }

    [Test]
    public void When_ImplementationOfMethodUsed_Should_GenerateBuilderAndExtensionMethods()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InlineInterface.Tests;

            public class Parent<T>
            {
                public interface IPerson<T>
                {
                    string GetName();

                    void SetName(string name);
                }
            }

            public class TestClass
            {
                public void TestMethod()
                {
                    var implementationOf = Implementation.Of<Parent<float>.IPerson<int>>();
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InlineInterface.Implementations.Macaron.InlineInterface.Tests
            {
                internal readonly record struct Parent_1_IPerson_1Builder<T0, T1>(
                    global::System.Func<string>? GetName_0 = null,
                    global::System.Action<string>? SetName_0 = null)
                {
                    private sealed class Impl : global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>
                    {
                        readonly global::System.Func<string> _getName_0;
                        readonly global::System.Action<string> _setName_0;

                        public Impl(
                            global::System.Func<string> getName_0,
                            global::System.Action<string> setName_0)
                        {
                            _getName_0 = getName_0;
                            _setName_0 = setName_0;
                        }

                        public string GetName() => _getName_0();

                        public void SetName(string name) => _setName_0(name);
                    }

                    public static global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build(Parent_1_IPerson_1Builder<T0, T1> builder)
                    {
                        return new Impl(
                            getName_0: builder.GetName_0 ?? throw new global::System.InvalidOperationException(),
                            setName_0: builder.SetName_0 ?? throw new global::System.InvalidOperationException());
                    }

                    public Parent_1_IPerson_1Builder<T0, T1> GetName(global::System.Func<string> impl) => this with { GetName_0 = impl };

                    public Parent_1_IPerson_1Builder<T0, T1> SetName(global::System.Action<string> impl) => this with { SetName_0 = impl };
                }
            }

            namespace Macaron.InlineInterface
            {
                internal static partial class ImplementationOfExtensions
                {
                    public static global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Create<T0, T1>(
                        this ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<global::Macaron.InlineInterface.Implementations.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>, global::Macaron.InlineInterface.Implementations.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>> configure)
                    {
                        return global::Macaron.InlineInterface.Implementations.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>.Build(configure(new global::Macaron.InlineInterface.Implementations.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>()));
                    }
                }
            }

            """
        );
    }

    [Test]
    public void When_TargetTypeIsNotInterface_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public class NotAnInterface { }

            public class Test { void M() => Implementation.Of<NotAnInterface>(); }
            """,
            expectedDiagnosticId: "MII0001"
        );
    }

    [Test]
    public void When_TargetTypeIsNullable_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface ITest { }

            public class Test { void M() => Implementation.Of<ITest?>(); }
            """,
            expectedDiagnosticId: "MII0002"
        );
    }

    [Test]
    public void When_TargetTypeHasProperty_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface IWithProperty { int Value { get; } }

            public class Test { void M() => Implementation.Of<IWithProperty>(); }
            """,
            expectedDiagnosticId: "MII0003"
        );
    }

    [Test]
    public void When_TargetTypeHasEvent_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;
            using System;

            public interface IWithEvent { event EventHandler Click; }

            public class Test { void M() => Implementation.Of<IWithEvent>(); }
            """,
            expectedDiagnosticId: "MII0004"
        );
    }

    [Test]
    public void When_TargetTypeHasGenericMethod_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface IWithGenericMethod { void M<T>(T arg); }

            public class Test { void M() => Implementation.Of<IWithGenericMethod>(); }
            """,
            expectedDiagnosticId: "MII0005"
        );
    }

    [Test]
    public void When_TargetTypeHasMethodWithRefParameters_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface IWithRefParam { void M(ref int arg); }

            public class Test { void M() => Implementation.Of<IWithRefParam>(); }
            """,
            expectedDiagnosticId: "MII0006"
        );
    }
}
