using System.Collections.Immutable;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Macaron.InlineInterface.Tests;

[TestFixture]
public class InlineInterfaceGeneratorTests
{
    private static (ImmutableArray<Diagnostic> diagnostics, string[] generatedCodes) CompileAndGetResults<T>(
        string sourceCode,
        Assembly[]? additionalAssemblies = null
    ) where T : IIncrementalGenerator, new()
    {
        var references = AppDomain
            .CurrentDomain
            .GetAssemblies()
            .Concat(additionalAssemblies ?? [])
            .Where(assembly => !assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>()
            .ToImmutableArray();

        var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
        var compilation = CSharpCompilation.Create(
            assemblyName: "Macaron.InlineInterface.Tests",
            syntaxTrees: [syntaxTree],
            references: references,
            options: new CSharpCompilationOptions(
                outputKind: OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );

        var generator = new T();
        var driver = CSharpGeneratorDriver.Create(generator);

        var result = driver.RunGenerators(compilation).GetRunResult().Results.Single();
        var generatedSources = result.GeneratedSources;
        var generatedCodes = generatedSources.Select(source => source.SourceText.ToString()).ToArray();

        var allDiagnostics = compilation.GetDiagnostics()
            .Concat(result.Diagnostics)
            .ToImmutableArray();

        return (allDiagnostics, generatedCodes);
    }

    private static void AssertGeneratedCode(string sourceCode, string[] expectedCodes)
    {
        var (_, generatedCodes) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        Assert.That(generatedCodes, Has.Length.EqualTo(expectedCodes.Length));

        foreach (var (generatedCode, index) in generatedCodes.Select((code, index) => (code, index)))
        {
            Assert.That(
                actual: generatedCode.ReplaceLineEndings(),
                expression: Is.EqualTo(expectedCodes[index].ReplaceLineEndings())
            );
        }
    }

    private static void AssertGeneratedCode(string sourceCode, int sourceIndex, string expected)
    {
        var (_, generatedCodes) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        Assert.That(
            actual: generatedCodes[sourceIndex].ReplaceLineEndings(),
            expression: Is.EqualTo(expected.ReplaceLineEndings())
        );
    }

    private static void AssertGeneratedCode(string sourceCode, string expected)
    {
        AssertGeneratedCode(sourceCode, sourceIndex: 0, expected);
    }

    private static void AssertDiagnostic(string sourceCode, string expectedDiagnosticId)
    {
        var (diagnostics, _) = CompileAndGetResults<InlineInterfaceGenerator>(
            sourceCode,
            additionalAssemblies: [typeof(ImplementationOf<>).Assembly]
        );

        var actualDiagnosticIds = diagnostics
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Select(diagnostic => diagnostic.Id)
            .ToArray();

        Assert.That(actualDiagnosticIds, Has.Some.Matches(expectedDiagnosticId));
    }

    [Test]
    public void When_ImplementationOfMethodUsed_Should_GenerateBuilderAndExtensionMethods()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;

            namespace Macaron.InlineInterface.Tests;

            public class Foo { }

            public class Parent<T> where T : class
            {
                public interface IPerson<T> where T : struct
                {
                    string GetName();

                    void SetName(string name);

                    string? FirstName { get; internal set; }

                    string LastName { get; }
                }
            }

            public class TestClass
            {
                public void TestMethod()
                {
                    var implementationOf = Implementation.Of<Parent<string>.IPerson<int>>();
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests
            {
                internal readonly struct Parent_1_IPerson_1Builder<T0, T1>
                    where T0 : class
                    where T1 : struct
                {
                    private sealed class Impl : global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>
                    {
                        private readonly global::System.Func<string?>? _getFirstName;
                        private readonly global::System.Action<string?>? _setFirstName;
                        private readonly global::System.Func<string>? _getLastName;
                        private readonly global::System.Func<string>? _getName_0;
                        private readonly global::System.Action<string>? _setName_0;

                        public Impl(
                            global::System.Func<string?>? getFirstName,
                            global::System.Action<string?>? setFirstName,
                            global::System.Func<string>? getLastName,
                            global::System.Func<string>? getName_0,
                            global::System.Action<string>? setName_0)
                        {
                            _getFirstName = getFirstName;
                            _setFirstName = setFirstName;
                            _getLastName = getLastName;
                            _getName_0 = getName_0;
                            _setName_0 = setName_0;
                        }

                        public string? FirstName
                        {
                            get => (_getFirstName ?? throw new global::System.NotImplementedException())();
                            set => (_setFirstName ?? throw new global::System.NotImplementedException())(value);
                        }

                        public string LastName
                        {
                            get => (_getLastName ?? throw new global::System.NotImplementedException())();
                        }

                        public string GetName() => (_getName_0 ?? throw new global::System.NotImplementedException())();

                        public void SetName(string name) => (_setName_0 ?? throw new global::System.NotImplementedException())(name);
                    }

                    private readonly bool _allowMissingImplementation;

                    private readonly global::System.Func<string?>? GetFirstName { get; init; } = null;

                    private readonly global::System.Action<string?>? SetFirstName { get; init; } = null;

                    private readonly global::System.Func<string>? GetLastName { get; init; } = null;

                    private readonly global::System.Func<string>? GetName_0 { get; init; } = null;

                    private readonly global::System.Action<string>? SetName_0 { get; init; } = null;

                    public Parent_1_IPerson_1Builder(
                        bool allowMissingImplementation,
                        global::System.Func<string?>? getFirstName = null,
                        global::System.Action<string?>? setFirstName = null,
                        global::System.Func<string>? getLastName = null,
                        global::System.Func<string>? getName_0 = null,
                        global::System.Action<string>? setName_0 = null)
                    {
                        _allowMissingImplementation = allowMissingImplementation;

                        GetFirstName = getFirstName;
                        SetFirstName = setFirstName;
                        GetLastName = getLastName;
                        GetName_0 = getName_0;
                        SetName_0 = setName_0;
                    }

                    public Parent_1_IPerson_1Builder<T0, T1> FirstName(global::System.Func<string?> getter, global::System.Action<string?> setter) => this with { GetFirstName = getter, SetFirstName = setter };

                    public Parent_1_IPerson_1Builder<T0, T1> LastName(global::System.Func<string> getter) => this with { GetLastName = getter };

                    public Parent_1_IPerson_1Builder<T0, T1> GetName(global::System.Func<string> impl) => this with { GetName_0 = impl };

                    public Parent_1_IPerson_1Builder<T0, T1> SetName(global::System.Action<string> impl) => this with { SetName_0 = impl };

                    public global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build(global::Macaron.InlineInterface.Tag _ = default)
                    {
                        return new Impl(
                            getFirstName: GetFirstName ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            setFirstName: SetFirstName ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            getLastName: GetLastName ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            getName_0: GetName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            setName_0: SetName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()));
                    }
                }
            }

            namespace Macaron.InlineInterface
            {
                internal static partial class ImplementationOfExtensions
                {
                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> FirstName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<string?> getter,
                        global::System.Action<string?> setter)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, getFirstName: getter, setFirstName: setter);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> LastName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<string> getter)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, getLastName: getter);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> GetName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<string> impl)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, getName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> SetName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Action<string> impl)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, setName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::Macaron.InlineInterface.Tag _ = default)
                        where T0 : class
                        where T1 : struct
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation).Build(_);
                    }
                }
            }

            """
        );
    }

    [Test]
    public void When_InterfaceHasEventMember_Should_GenerateEventCollection()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;

            namespace Macaron.InlineInterface.Tests;

            public class Foo { }

            public class Parent<T>
            {
                public interface IPerson<T>
                {
                    event Func<Foo?, string> NameChanged;

                    void SetName(string name);

                    string LastName { get; }
                }
            }

            public class TestClass
            {
                public void TestMethod()
                {
                    var implementationOf = Implementation.Of<Parent<string>.IPerson<int>>();
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests
            {
                internal readonly struct Parent_1_IPerson_1Builder<T0, T1>
                {
                    public sealed class EventCollection
                    {
                        public global::System.Func<global::Macaron.InlineInterface.Tests.Foo?, string>? NameChanged;
                    }

                    private sealed class Impl : global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>
                    {
                        private readonly EventCollection _eventCollection = new();
                        private readonly global::System.Func<EventCollection, string>? _getLastName;
                        private readonly global::System.Action<EventCollection, string>? _setName_0;

                        public Impl(
                            global::System.Func<EventCollection, string>? getLastName,
                            global::System.Action<EventCollection, string>? setName_0)
                        {
                            _getLastName = getLastName;
                            _setName_0 = setName_0;
                        }

                        public event global::System.Func<global::Macaron.InlineInterface.Tests.Foo?, string>? NameChanged
                        {
                            add => _eventCollection.NameChanged += value;
                            remove => _eventCollection.NameChanged -= value;
                        }

                        public string LastName
                        {
                            get => (_getLastName ?? throw new global::System.NotImplementedException())(_eventCollection);
                        }

                        public void SetName(string name) => (_setName_0 ?? throw new global::System.NotImplementedException())(_eventCollection, name);
                    }

                    private readonly bool _allowMissingImplementation;

                    private readonly global::System.Func<EventCollection, string>? GetLastName { get; init; } = null;

                    private readonly global::System.Action<EventCollection, string>? SetName_0 { get; init; } = null;

                    public Parent_1_IPerson_1Builder(
                        bool allowMissingImplementation,
                        global::System.Func<EventCollection, string>? getLastName = null,
                        global::System.Action<EventCollection, string>? setName_0 = null)
                    {
                        _allowMissingImplementation = allowMissingImplementation;

                        GetLastName = getLastName;
                        SetName_0 = setName_0;
                    }

                    public Parent_1_IPerson_1Builder<T0, T1> LastName(global::System.Func<EventCollection, string> getter) => this with { GetLastName = getter };

                    public Parent_1_IPerson_1Builder<T0, T1> SetName(global::System.Action<EventCollection, string> impl) => this with { SetName_0 = impl };

                    public global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build(global::Macaron.InlineInterface.Tag _ = default)
                    {
                        return new Impl(
                            getLastName: GetLastName ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()),
                            setName_0: SetName_0 ?? (_allowMissingImplementation ? null : throw new global::System.InvalidOperationException()));
                    }
                }
            }

            namespace Macaron.InlineInterface
            {
                internal static partial class ImplementationOfExtensions
                {
                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> LastName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Func<global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>.EventCollection, string> getter)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, getLastName: getter);
                    }

                    public static global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1> SetName<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::System.Action<global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>.EventCollection, string> impl)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation, setName_0: impl);
                    }

                    public static global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1> Build<T0, T1>(
                        this global::Macaron.InlineInterface.ImplementationOf<global::Macaron.InlineInterface.Tests.Parent<T0>.IPerson<T1>> implementationOf,
                        global::Macaron.InlineInterface.Tag _ = default)
                    {
                        return new global::Macaron.InlineInterface.Generated.Macaron.InlineInterface.Tests.Parent_1_IPerson_1Builder<T0, T1>(allowMissingImplementation: implementationOf.AllowMissingImplementation).Build(_);
                    }
                }
            }

            """
        );
    }

    [Test]
    public void When_TargetTypeIsNotInterface_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public class NotAnInterface { }

            public class Test { void M() => Implementation.Of<NotAnInterface>(); }
            """,
            expectedDiagnosticId: "MII0001"
        );
    }

    [Test]
    public void When_TargetTypeIsNullable_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface ITest { }

            public class Test { void M() => Implementation.Of<ITest?>(); }
            """,
            expectedDiagnosticId: "MII0002"
        );
    }

    [Test]
    public void When_TargetTypeHasGenericMethod_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface IWithGenericMethod { void M<T>(T arg); }

            public class Test { void M() => Implementation.Of<IWithGenericMethod>(); }
            """,
            expectedDiagnosticId: "MII0003"
        );
    }

    [Test]
    public void When_TargetTypeHasMethodWithRefParameters_Should_ReportDiagnostic()
    {
        AssertDiagnostic(
            sourceCode:
            """
            using Macaron.InlineInterface;

            public interface IWithRefParam { void M(ref int arg); }

            public class Test { void M() => Implementation.Of<IWithRefParam>(); }
            """,
            expectedDiagnosticId: "MII0004"
        );
    }
}
