<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Macaron.InlineInterface</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Macaron.InlineInterface</RootNamespace>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Gyu Song</Authors>
    <PackageId>Macaron.InlineInterface</PackageId>
    <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/songkyoo/InlineInterface</RepositoryUrl>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InlineInterface.Core\InlineInterface.Core.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\InlineInterface.Generator\InlineInterface.Generator.csproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\InlineInterface.Core\bin\$(Configuration)\netstandard2.0\Macaron.InlineInterface.Core.dll" Pack="true" PackagePath="lib/netstandard2.0" />
    <None Include="..\InlineInterface.Core\bin\$(Configuration)\netstandard2.0\Macaron.InlineInterface.Core.dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
    <None Include="..\InlineInterface.Generator\bin\$(Configuration)\netstandard2.0\Macaron.InlineInterface.Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
  </ItemGroup>

</Project>
